# The Docker image that will be used to build your app
image: node:18.16.0
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli
    - npm install 
    - npm run gitlabBuild
  artifacts:
    paths:
      - public
  only:
    - main