# The Docker image that will be used to build your app
image: node:latest
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli
    - npm install 
    - ng build --prod --base-href /spa-ui/
    - mkdir public
    - mv dist/spa-ui/* public/
    - npm run gitlabBuild
  artifacts:
    paths:
      - public
  only:
    - main